# name å¯ä»¥è‡ªå®šä¹‰
name: Deploy GitHub Pages

# è§¦å‘æ¡ä»¶ï¼šåœ¨ push åˆ° main åˆ†æ”¯å
on:
  push:
    branches:
      - main

# ä»»åŠ¡
jobs:
  build-and-deploy:
    # æœåŠ¡å™¨ç¯å¢ƒï¼šæœ€æ–°ç‰ˆ Ubuntu
    runs-on: ubuntu-latest
    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # è®¾ç½®Nodeç¯å¢ƒ
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # è®¾ç½®pnpmç¯å¢ƒ
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1

      # å®‰è£…ä¾èµ–
      - name: Install ğŸ”§
        run: pnpm install
      
      # æ‰“åŒ…
      - name: Build ğŸ—ï¸
        run: pnpm run docs:build
        # env:
        #   NODE_ENV: production

      # ç”Ÿæˆé™æ€æ–‡ä»¶
      # - name: Build
      #   run: pnpm install && pnpm run docs:build

      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy to GH Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist # vitepress ç”Ÿæˆçš„é™æ€æ–‡ä»¶å­˜æ”¾çš„åœ°æ–¹


